# Generated by Django 5.2.9 on 2026-04-05 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='hire_data',
            new_name='hire_date',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='salart',
            new_name='salary',
        ),
    ]
