# Generated by Django 5.2.9 on 2026-04-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_rename_hire_data_employee_hire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
    ]
